"""empty message

Revision ID: 22f22eca202e
Revises: cc40a3ab714b
Create Date: 2018-11-29 11:10:51.491708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f22eca202e'
down_revision = 'cc40a3ab714b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('address', sa.Text(), nullable=True))
    op.alter_column('room', 'allow_parking',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('room', 'allow_smoking',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room', 'allow_smoking',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('room', 'allow_parking',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('room', 'address')
    # ### end Alembic commands ###
