"""empty message

Revision ID: 9796ff4186b2
Revises: 7c59668a93a7
Create Date: 2019-05-13 09:49:50.248566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9796ff4186b2'
down_revision = '7c59668a93a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('img_1', sa.Text(), nullable=True))
    op.add_column('room', sa.Column('img_2', sa.Text(), nullable=True))
    op.add_column('room', sa.Column('img_3', sa.Text(), nullable=True))
    op.add_column('room', sa.Column('img_main', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'img_main')
    op.drop_column('room', 'img_3')
    op.drop_column('room', 'img_2')
    op.drop_column('room', 'img_1')
    # ### end Alembic commands ###
