"""empty message

Revision ID: e8cc639318fa
Revises: 
Create Date: 2018-11-28 08:33:48.969729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8cc639318fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('is_room_master', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('body_capacity', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('allow_smoking', sa.Boolean(), nullable=False),
    sa.Column('allow_parking', sa.Boolean(), nullable=False),
    sa.Column('allow_children', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    #op.drop_table('table1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('table1',
    #sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    #sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    #sa.Column('age', sa.BIGINT(), autoincrement=False, nullable=True),
    #sa.UniqueConstraint('id', name='table1_id_key')
    #)
    op.drop_table('room')
    op.drop_table('user')
    # ### end Alembic commands ###
